(global-set-key (kbd "s-J") 'join-line)
(global-set-key (kbd "C-x C-f") 'find-file)
(global-set-key (kbd "s-=") 'text-scale-increase)
(global-set-key (kbd "s--") 'text-scale-decrease)
(global-set-key (kbd "C-c SPC") 'ace-jump-mode)
(global-set-key (kbd "C-]") 'pop-to-mark-command)
